image: node:12

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - docs/node_modules/
    - packages/core/node_modules/
    - packages/react/node_modules/

stages:
  - prepare
  - codequality
  - build
  - test
  - deploy

install:
  stage: prepare
  script:
    - npm install
    - npm run bootstrap

eslint:
  stage: codequality
  script:
    - npm run lint:es

stylelint:
  stage: codequality
  script:
    - npm run lint:style

prettier:
  stage: codequality
  script:
    - npm run lint:prettier

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - packages/*/dist
    expire_in: 30 days

test:unit:
  stage: test
  script:
    - npm run coverage
  dependencies:
    - build

pages:
  stage: deploy
  environment:
    name: docs
    url: $CI_PAGES_URL
  variables:
    VUEPRESS_BASE: /platform/$CI_PROJECT_NAME/
  before_script:
    - npm run build:stories -- -- -o ../../docs/.vuepress/public/storybook
  script:
    - npm run build:docs
  artifacts:
    paths:
      - public
  only:
    - master
