image: node:10

stages:
  - codequality
  # - test
  - build

before_script:
  - npm ci
  - npm run lerna:bootstrap

eslint:
  stage: codequality
  script:
    - npm run lint:es

stylelint:
  stage: codequality
  script:
    - npm run lint:style

prettier:
  stage: codequality
  script:
    - npm run lint:prettier

build:components:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - packages/components/dist
    expire_in: 30 days

pages:
  stage: build
  environment:
    name: docs
    url: $CI_PAGES_URL
  variables:
    VUEPRESS_BASE: /platform/$CI_PROJECT_NAME/
  script:
    - npm run docs:build -- --dest public
  artifacts:
    paths:
      - public
  only:
    - master
