image: node:10

stages:
  - codequality
  # - test
  # - build

before_script:
  - npm ci

eslint:
  stage: codequality
  script:
    - npm run lint:es

stylelint:
  stage: codequality
  script:
    - npm run lint:style

prettier:
  stage: codequality
  script:
    - npm run lint:prettier
