image: node:10

variables:
  SCOPE: "@nds"

stages:
  - codequality
  # - test
  - build

before_script:
  - npm ci

eslint:
  stage: codequality
  script:
    - npm run lint:es

stylelint:
  stage: codequality
  script:
    - npm run lint:style

prettier:
  stage: codequality
  script:
    - npm run lint:prettier

build:components:
  stage: build
  script:
    - npm run build -- --scope $SCOPE/components
  artifacts:
    paths:
      - packages/components/dist
    expire_in: 30 days
