image: node:10

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - packages/**/node_modules/

stages:
  - install
  - codequality
  # - test
  - build

install:
  stage: install
  script:
    - npm install
    - npm run bootstrap

eslint:
  stage: codequality
  script:
    - npm run lint:es

stylelint:
  stage: codequality
  script:
    - npm run lint:style

prettier:
  stage: codequality
  script:
    - npm run lint:prettier

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - packages/**/dist
    expire_in: 30 days

pages:
  stage: build
  environment:
    name: docs
    url: $CI_PAGES_URL
  variables:
    VUEPRESS_BASE: /platform/$CI_PROJECT_NAME/
  script:
    - npm run build:docs
  artifacts:
    paths:
      - public
  only:
    - master
