image: node

stages:
  - codequality
  # - test
  - build

before_script:
  - npm ci
  - npm run bootstrap

eslint:
  stage: codequality
  script:
    - npm run lint:es

stylelint:
  stage: codequality
  script:
    - npm run lint:style

prettier:
  stage: codequality
  script:
    - npm run lint:prettier

build:core:
  stage: build
  script:
    - npm run build:core
  artifacts:
    paths:
      - packages/core/dist
    expire_in: 30 days

pages:
  stage: build
  environment:
    name: docs
    url: $CI_PAGES_URL
  variables:
    VUEPRESS_BASE: /platform/$CI_PROJECT_NAME/
  script:
    - npm run build:docs
  artifacts:
    paths:
      - public
  only:
    - master
