name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node.js environment 🌄
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Restore cache 💵
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: NPM install 📦
        run: npm install
      - name: Lerna bootstrap 👢
        run: npm run bootstrap -- --no-ci

  eslint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node.js environment 🌄
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: ESLint ✨
        run: npm run lint:es

  stylelint:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node.js environment 🌄
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Stylelint ✨
        run: npm run lint:style

  prettier:
    needs: prepare
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node.js environment 🌄
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Prettier ✨
        run: npm run lint:prettier

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node.js environment 🌄
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Test 🧪
        run: npm run coverage
      - name: Codecov ☂
        uses: codecov/codecov-action@v1
        with:
          directory: coverage

  build-lib:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
      - name: Setup Node.js environment 🌄
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Build 🔧
        run: npm run build

  deploy-docs-pages:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Setup Node.js environment 🌄
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - name: Build docs 📄
        run: npm run build:docs
        env:
          PATH_PREFIX: /design-system
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
