name: Integration

on: [pull_request]

jobs:
  deploy-docs-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: NPM install 📦
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lerna bootstrap 👢
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap
      - name: Build docs 📄
        run: npm run build:docs
        env:
          PATH_PREFIX: /${{ github.ref }}/
      - name: Deploy 🚀
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "public"
          DEST_DIR: ${{ github.ref }}
