name: Review

on: [pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        id: cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: NPM install 📦
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lerna bootstrap 👢
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run bootstrap
      - name: Build Sassdoc 💄
        run: npm run build:sassdoc -- --dest docs/static/sassdoc
      - name: Build Storybook 📚
        run: npm run build:stories -- -- --output-dir ../../docs/static/storybook
      - name: Build docs 📄
        run: npm run build:docs
        env:
          PATH_PREFIX: /${{ github.head_ref }}/
      - run: mv docs/public public
      - name: Deploy 🚀
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          SOURCE_DIR: "public"
          DEST_DIR: ${{ github.head_ref }}
      - name: Clean 🧹
        if: github.event.pull_request.merged == true
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PATH_TO_DELETE: ${{ github.head_ref }}
